# Generated by Django 3.2.5 on 2021-07-25 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence_name', models.CharField(max_length=128, verbose_name='Название компетенции:')),
                ('box1', models.TextField(blank=True, verbose_name='Ты можешь считать ее развитой, если')),
                ('box2', models.TextField(blank=True, verbose_name='Задуматься о том, чтобы подтянуть эту компетенцию, стоит, если')),
                ('box3', models.TextField(blank=True, verbose_name='Вариант развития №1:')),
                ('box4', models.TextField(blank=True, verbose_name='Вариант развития №2:')),
                ('box5', models.TextField(blank=True, verbose_name='Вариант развития №3:')),
                ('box6', models.TextField(blank=True, verbose_name='Вариант развития №4:')),
                ('box7', models.TextField(blank=True, verbose_name='Вариант развития №5:')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.TextField(blank=True, max_length=256, verbose_name='Имя лидера')),
                ('city', models.TextField(blank=True, max_length=256, null=True, verbose_name='Город')),
                ('company', models.TextField(blank=True, max_length=256, verbose_name='Название компании')),
                ('position', models.TextField(blank=True, max_length=256, verbose_name='Должность')),
                ('phone', models.TextField(blank=True, max_length=256, verbose_name='Телефон')),
                ('email', models.TextField(blank=True, max_length=128, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Контакт лидера',
                'verbose_name_plural': 'Контакты лидеров',
                'ordering': ('city',),
            },
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128, verbose_name='Регион')),
                ('course', models.CharField(max_length=128, verbose_name='Направление')),
                ('contact', models.TextField(verbose_name='Контакты в регионе')),
            ],
            options={
                'verbose_name': 'Cоциальная адаптация молодежи',
                'verbose_name_plural': 'Cоциальная адаптация молодежи',
                'ordering': ('city',),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=128, verbose_name='Направление')),
                ('contact', models.TextField(verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'База ресурсов',
                'verbose_name_plural': 'База ресурсов',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('uid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('surname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=256, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=128, verbose_name='Телефон')),
                ('city', models.CharField(max_length=256, verbose_name='Город')),
                ('company', models.CharField(blank=True, max_length=256, verbose_name='Компания')),
                ('position', models.CharField(blank=True, max_length=256, verbose_name='Позиция')),
                ('consent', models.BooleanField(verbose_name='Согласие на ОПД')),
                ('competence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gigaapp.competence', verbose_name='Выбранная компетенция')),
                ('contacts', models.ManyToManyField(blank=True, to='gigaapp.Contact', verbose_name='Полученные контакты')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gigaapp.curator', verbose_name='Cоциальная адаптация молодежи')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gigaapp.resource', verbose_name='Направление развития')),
            ],
            options={
                'verbose_name': 'Волонтер',
                'verbose_name_plural': 'Волонтеры',
            },
        ),
    ]
