# Generated by Django 3.2.5 on 2021-07-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.CharField(blank=True, max_length=256, verbose_name='Email'),
        ),
    ]
